### PR TITLE
fix(scripts): Update `mintConditionalTokens` to Handle Fractional Units

### LINKED ISSUE #245: mintConditionalTokens doesn't accept fractional units of tokens
https://github.com/metaDAOproject/futarchy/blob/97b19885ee5db7942896ecb06856e5198ad21b08/scripts/main.ts#L756C68-L756C77

https://github.com/metaDAOproject/futarchy/blob/97b19885ee5db7942896ecb06856e5198ad21b08/sdk/src/ConditionalVaultClient.ts#L69

If a user was to pass a fractional amount it gets cast as a big number and rounded to zero if not a whole number, ideally it can be parsed and cast as a BN after calculating the fractional amount.

CC: @inkprojectsol

### PR DESCRIPTION
**Pull request by 0xIchigo**
This PR aims to resolve #245 by:
- Converting the user-provided `input` to the smallest unit of the token based on its decimals
- Calculate the scaled amount by multiplying the input amount by 10^(token's decimals)
- Round the scaled amount to the nearest integer
- Create a new `BN` with the scaled, rounded amount

This PR also adds the `getTokenDecimals` helper function to streamline fetching a token's decimals

### CODE REVIEW

**Comment by Henry-E** [comment]
is this why when someone tries to place an order of 0.69 base tokens it turns into an order for 0.68989898 base tokens?

**Comment by R-K-H** [comment]
> is this why when someone tries to place an order of 0.69 base tokens it turns into an order for 0.68989898 base tokens?

Nah the UI doesn't actually use this, it uses the create IX with the rpc() call and the amount output is actually produced through the simSwap functionality.

**Review by R-K-H — APPROVED** [review]
Thanks for doing this!

**Review by R-K-H — CHANGES_REQUESTED** [review]
Actually this happens in another place as well, just something which would wrap up the issue and complete it...

https://github.com/metaDAOproject/futarchy/blob/97b19885ee5db7942896ecb06856e5198ad21b08/sdk/src/ConditionalVaultClient.ts#L80

**Comment by 0xIchigo** [comment]
Should be all good now @R-K-H! I opted to just re-use `getTokenDecimals` as a more standard, reusable way of fetching a token's decimals

**Review by R-K-H — APPROVED** [review]
LGTM! Thanks for the update provides some higher functionality for the SDK use vs folks diving into the mintConditionalTokensIx() :)

File: sdk/src/ConditionalVaultClient.ts [hunk 1]
```diff
@@ -73,18 +75,20 @@ export class ConditionalVaultClient {
   ) {
     const storedVault = await this.getVault(vault);
 
-    return (
-      this.mintConditionalTokensIx(
+    try {
+      const tokenDecimals = await getTokenDecimals(storedVault.underlyingTokenMint);
```
Comment (metaproph3t) [inline sdk/src/ConditionalVaultClient.ts]: you can just use storedVault.decimals for this and don't need to make the extra call

File: sdk/src/ConditionalVaultClient.ts [hunk 2]
```diff
@@ -24,6 +24,8 @@ import {
   getAssociatedTokenAddressSync,
 } from "@solana/spl-token";
 
+import { getTokenDecimals } from "../../scripts/main";
```
Comment (metaproph3t) [inline sdk/src/ConditionalVaultClient.ts]: idk if this will work

**Review by metaproph3t — CHANGES_REQUESTED** [review]
Thanks for this! Left 1 comment
